platform :ios, '8.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
target "yunbaolive" do
#图片
pod 'SDWebImage', '~>3.8'
#网络请求
pod 'MJRefresh'
pod 'AFNetworking','~> 3.0’
#极光
pod 'JPush'
pod 'JMessage'
#极光日志打印
pod 'CocoaLumberjack'
#bugly
pod 'Bugly', '~> 2.4.6'
#支付宝
pod 'AliPay', '~> 2.1.2'
pod 'OpenSSL-for-iOS', '~> 1.0.2.d.1'
#UI
pod 'Masonry', '~> 1.0.1'
#分享
pod 'mob_sharesdk'
pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
#pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'   #（微信sdk不带支付的命令）
pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull' #（微信sdk带支付的命令，和上面不带支付的不能共存，只能选择一个）
pod 'mob_sharesdk/ShareSDKPlatforms/Facebook'
pod 'mob_sharesdk/ShareSDKPlatforms/Twitter'
#SVGAPlayer
pod 'SVGAPlayer'
#弹窗
pod 'CWStatusBarNotification', '~> 2.3.5'
#金山SDK
pod 'libksygpulive/libksygpulive'
#七牛
pod 'Qiniu'
#腾讯SDK
#pod 'TXLiteAVSDK_UGC', '3.9.2749'
pod 'TXLiteAVSDK_Professional', '~> 5.4.6097'
#腾讯上传
pod 'QCloudCOSXML'

#AT 功能
pod 'HPGrowingTextView'
#YYImage用来加载gif
pod 'YYWebImage'
#友盟统计
pod 'UMCCommon'
pod 'UMCAnalytics'
pod 'UMCSecurityPlugins'
#  轮播图
pod 'SDCycleScrollView'
use_frameworks!
#socket.io
pod 'Socket.IO-Client-Swift', '~> 15.2.0'
pod 'MBProgressHUD'
pod 'EBBannerView'

end
